name: Go CI

on:
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Run Linter
        run: golangci-lint run ./...
      - name: Run Tests
        run: go test ./... -v
